version: "3.5"

services:
  isolr_nodejs:
    container_name: isolr_nodejs
    build: ./isolr
    ports:
      - 3000:3000
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    volumes:
      - './isolr:/usr/src/solar '
